aws-solutions/research-service-workbench-on-aws

- solutions/swb-reference/SWBv2.postman_collection.json
Missing Datasets API examples in postman collection.
Adding DS API examples.
Fixing attributes in list environments API example.
Checklist:
> docs: add datasets APIs

- solutions/swb-reference/README.md
- solutions/swb-reference/SETUP_v2p1.md
docs: update documentation with information about CWL
Checklist:
> docs: update documentation with information about CWL

- .gitignore
- solutions/swb-reference/package.json
- solutions/swb-reference/src/constants.ts
- solutions/swb-ui/infrastructure/package.json
- solutions/swb-ui/infrastructure/src/constants.ts
- solutions/swb-ui/scripts/deploy.sh
- solutions/swb-ui/scripts/dev.sh
Create .json files instead of .js for deployment outputs
Checklist:
* [ x ] Have you successfully deployed to an AWS account with your changes?
> fix(swb deployment): fix files outputs to be json

- solutions/swb-reference/jest.config.js
N/A
Fix config path for integ test settings.
Checklist:
> fix: config path for integ test

- solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
GALI-1576
Add positive and negative integ tests for env list.
Checklist:
> test: valid and invalid env status

- .github/workflows/ignore-license-checker.yml
- solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
> fix: add ignore license checker when package.json changes are not detected

- .github/workflows/deploy-integration-swb-reference.yml
- .gitignore
- solutions/swb-reference/SWBv2.postman_collection.json
- solutions/swb-reference/integration-tests/config/testEnv.yaml
- solutions/swb-reference/integration-tests/support/clientSession.ts
GALI-1628
-add cookie authorization to postman template and integration tests
-add integration test running to pipeline
-add UI deployment to pipeline
Checklist:
* [ x ] Have you successfully deployed to an AWS account with your changes?
> feat: integration test pipeline

- DEVELOPMENT.md
> docs: rush add instructions for developers

- common/changes/@aws/workbench-core-datasets-ui/fix-datasets-ui_2022-09-02-17-29.json
- workbench-core/datasets-ui/src/api/datasets.ts
- workbench-core/datasets-ui/src/pages/index.tsx
GALI-1609
Strip down DS list page for minimum functionality to begin with.
Checklist:
> fix: datasets base UI page

- common/changes/@aws/workbench-core-datasets-ui/docs-integration-testing-readme_2022-09-07-16-15.json
- solutions/swb-reference/README.md
- solutions/swb-ui/package.json
- workbench-core/datasets-ui/package.json
> docs(integration testing): update readme for integration testing

- common/changes/@aws/workbench-core-accounts-ui/fix-readme-commit_2022-09-16-19-20.json
- common/changes/@aws/workbench-core-environments-ui/fix-readme-commit_2022-09-16-19-20.json
- workbench-core/accounts-ui/README.md
- workbench-core/environments-ui/README.md
N/A
Readme files for new packages updated with coverage report.
Checklist:
> fix: readme file coverage report for new packages

- common/changes/@aws/workbench-core-accounts-ui/readme-commit_2022-09-19-21-22.json
- common/changes/@aws/workbench-core-environments-ui/readme-commit_2022-09-19-21-22.json
- solutions/swb-ui/package.json
- workbench-core/accounts-ui/config/heft.json
- workbench-core/accounts-ui/config/jest.config.json
- workbench-core/accounts-ui/config/rig.json
- workbench-core/environments-ui/package.json
Add heft config for accounts-ui package
Checklist:
> chore: fix for accounts-ui Readme commit build

- common/changes/@aws/workbench-core-accounts-ui/fix-env-ui-package-heft_2022-09-19-21-56.json
- common/changes/@aws/workbench-core-environments-ui/fix-env-ui-package-heft_2022-09-19-21-56.json
- workbench-core/accounts-ui/README.md
- workbench-core/environments-ui/README.md
- workbench-core/environments-ui/config/heft.json
- workbench-core/environments-ui/config/jest.config.json
- workbench-core/environments-ui/config/rig.json
N/A
Add heft config for env-ui package
Checklist:
> fix: env UI package heft

- solutions/swb-reference/SWBv2.postman_collection.json
Add correct path for terminating an environment in POSTMAN
Checklist:
> fix: terminate postman

- .github/workflows/build-and-test.yml
- .github/workflows/cfn-nag.yml
- .github/workflows/test-deletion.yml
> chore: test branch deletion

- solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml
GALI-1857
Create a new onboarding configuration tempalte that allows for BYON
Checklist:
> feat: onboarding template byon

- common/changes/@aws/workbench-core-accounts-ui/sevu-fix-add-eslint-config_2022-10-06-22-09.json
- common/changes/@aws/workbench-core-datasets-ui/sevu-fix-add-eslint-config_2022-10-06-22-09.json
- common/changes/@aws/workbench-core-environments-ui/sevu-fix-add-eslint-config_2022-10-06-22-09.json
- common/changes/@aws/workbench-core-swb-common-ui/sevu-fix-add-eslint-config_2022-10-06-22-09.json
- common/config/rush/pnpm-lock.yaml
- workbench-core/accounts-ui/package.json
- workbench-core/datasets-ui/package.json
- workbench-core/environments-ui/package.json
- workbench-core/swb-common-ui/package.json
Add missing eslint config
After fix:
Issue:
Only TS warnings are shown
> fix(ui): add missing eslint config

- common/changes/@aws/workbench-core-swb-common-ui/sevu-feat-GALI-1889-file-upload-component_2022-10-07-21-45.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- workbench-core/datasets-ui/package.json
- workbench-core/swb-common-ui/package.json
- workbench-core/swb-common-ui/src/common/utils.ts
- workbench-core/swb-common-ui/src/components/FileUpload/FileUploadComponent.tsx
- workbench-core/swb-common-ui/src/components/FileUpload/SelectedFile.tsx
- workbench-core/swb-common-ui/src/components/FileUpload/SelectedFileList.tsx
- workbench-core/swb-common-ui/src/components/FileUpload/models/FileUpload.ts
- workbench-core/swb-common-ui/src/components/FileUpload/utils.ts
- workbench-core/swb-common-ui/src/index.tsx
Issue #, if available: GALI-1889
Description of changes: file upload component
> feat: file upload component

- common/config/rush/pnpm-lock.yaml
- solutions/swb-reference/src/backendAPI.ts
- workbench-core/audit/README.md
- workbench-core/audit/package.json
- workbench-core/audit/src/auditLogger.test.ts
- workbench-core/audit/src/auditLogger.ts
- workbench-core/audit/src/index.ts
- workbench-core/base/README.md
- workbench-core/base/package.json
- workbench-core/base/src/index.ts
- workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
- workbench-core/example/infrastructure/src/__tests__/__snapshots__/infrastructure-stack.test.ts.snap
removes circular dependency of base -> audit -> authz -> base
Checklist:
> refactor: move AuditLogger from base to audit

- common/changes/@aws/swb-app/fix-integration-tests-fix_2022-10-13-20-02.json
- common/changes/@aws/workbench-core-base/fix-integration-tests-fix_2022-10-13-20-02.json
- common/changes/@aws/workbench-core-datasets/fix-integration-tests-fix_2022-10-13-20-02.json
- solutions/swb-app/package.json
- solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
- workbench-core/base/package.json
- workbench-core/datasets/src/dataSetMetadataPlugin.ts
- workbench-core/datasets/src/dataSetService.ts
> fix: fix datasets integration tests

- solutions/swb-reference/integration-tests/support/resources/datasets/datasets.ts
- solutions/swb-reference/package.json
> fix: datasets integration test fix

- solutions/swb-reference/src/SWBStack.ts
- solutions/swb-reference/src/config/demo.yaml
- solutions/swb-reference/src/config/example.yaml
- solutions/swb-reference/src/config/testEnv.yaml
- solutions/swb-reference/src/constants.ts
- solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.test.ts
- solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.ts
- solutions/swb-reference/src/infra/SWBVpc.test.ts
- solutions/swb-reference/src/infra/SWBVpc.ts
- workbench-core/environments/README.md
* Adding VPC creation with ability for user to pass in a VPC ID
* Allowing user to pass in Subnets for ALB
* Creating ALB
Checklist:
> feat(swb-reference): adding VPC and ALB resources

- common/changes/@aws/swb-app/GALI-1839_EnvTypeCreation_2022-10-15-06-01.json
- common/changes/@aws/workbench-core-base/GALI-1839_EnvTypeCreation_2022-10-15-06-01.json
- common/changes/@aws/workbench-core-datasets/GALI-1839_EnvTypeCreation_2022-10-15-06-01.json
- common/changes/@aws/workbench-core-environments/GALI-1839_EnvTypeCreation_2022-10-15-06-01.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- solutions/swb-app/src/environmentTypeConfigRoutes.ts
- solutions/swb-app/src/environmentTypeRoutes.ts
- solutions/swb-app/src/staticRouteConfig.ts
- solutions/swb-reference/integration-tests/config/testEnv.yaml
- solutions/swb-reference/src/SWBStack.ts
- solutions/swb-reference/src/accountHandlerLambda.ts
- workbench-core/base/README.md
- workbench-core/base/package.json
- workbench-core/base/src/aws/helpers/cloudFormationTemplate.ts
- workbench-core/base/src/aws/helpers/s3Service.ts
- workbench-core/base/src/aws/helpers/serviceCatalogService.ts
- workbench-core/base/src/index.ts
- workbench-core/base/src/utilities/textUtil.ts
- workbench-core/environments/README.md
- workbench-core/environments/src/handlers/environmentTypeHandler.test.ts
- workbench-core/environments/src/handlers/environmentTypeHandler.ts
- workbench-core/environments/src/index.ts
- workbench-core/environments/src/interfaces/environmentType.ts
- workbench-core/environments/src/schemas/createEnvironmentType.ts
- workbench-core/environments/src/services/environmentTypeService.test.ts
- workbench-core/environments/src/services/environmentTypeService.ts
Gali-1839
Add environment types creation in account handler and update format
Checklist:
* [x ] Have you successfully deployed to an AWS account with your changes?
* [x ] Have you written new tests for your core changes, as applicable?
> feat:  env type creation

- common/changes/@aws/workbench-core-base/sevu-bugs-fix-no-such-entity_2022-10-20-16-00.json
- workbench-core/base/README.md
- workbench-core/base/src/utilities/iamRoleCloneService.test.ts
- workbench-core/base/src/utilities/iamRoleCloneService.ts
Description of changes: 
fix incorrect exception check due to that status handler lambda would've never succeeded. Previous validation fails due to incorrect name check (see second screenshot)
Checklist:
> fix: no such entity exception

- common/changes/@aws/workbench-core-infrastructure/fix-cognito-construct-update_2022-10-20-20-33.json
- workbench-core/infrastructure/docs/workbenchCognito.md
- workbench-core/infrastructure/src/workbenchCognito.test.ts
- workbench-core/infrastructure/src/workbenchCognito.ts
- changed MFA default to OPTIONAL
- changed accessTokenValidity default to 7 days
- added optional parameters to change these values
- added more thorough unit tests
Checklist:
> feat: cognito construct update

- common/changes/@aws/workbench-core-infrastructure/fix-cognito-construct-fix_2022-10-20-23-53.json
- workbench-core/infrastructure/src/workbenchCognito.ts
Added default MFA type to OTP.
Checklist:
> fix: cognito construct fix

- common/changes/@aws/swb-app/fix-route-validation-etc_2022-10-21-21-40.json
- solutions/swb-app/src/environmentTypeConfigRoutes.ts
Update route validation for ETC to accept ETC ID with prefixes.
**Test**
API work as expected using POSTMAN
Checklist:
> fix: route validation for ETC

- solutions/swb-reference/SWBv2.postman_collection.json
GALI-1777 and GALI-1778 follow up
Added Cost Center requests to postman
Checklist:
> chore: Add Cost Center to Postman

- workbench-core/authorization/README.md
- workbench-core/authorization/src/__mocks__/authorizationPlugin.ts
- workbench-core/authorization/src/authorizationPlugin.ts
- workbench-core/authorization/src/authorizationService.ts
- workbench-core/authorization/src/caslAuthorizationPlugin.test.ts
- workbench-core/authorization/src/caslAuthorizationPlugin.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicPermissionsPluginInputs.ts
- workbench-core/authorization/src/index.ts
- workbench-core/authorization/src/operation.ts
- workbench-core/authorization/src/permissionsPlugin.ts
- workbench-core/authorization/src/routesMap.ts
- workbench-core/authorization/src/staticPermissionsPlugin.ts
- workbench-core/example/infrastructure/src/__tests__/__snapshots__/infrastructure-stack.test.ts.snap
- isAuthorizedOnDynamicOperations
Checklist:
> feat: add isAuthorizedOnDynamicOperations to CASL Authorization Plugin

- solutions/swb-reference/src/SWBStack.ts
- solutions/swb-reference/src/config/demo.yaml
- solutions/swb-reference/src/config/example.yaml
- solutions/swb-reference/src/config/testEnv.yaml
- solutions/swb-reference/src/constants.ts
Issue #, if available: GALI-1545
use cert and zone name provided by user
Checklist:
> feat: use cert provided by admin

- common/changes/@aws/workbench-core-authentication/topic-user-management-error-message-refactor_2022-10-26-22-59.json
- workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.test.ts
- workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.ts
- workbench-core/authentication/src/userManagementPlugin.ts
- workbench-core/authentication/src/userManagementService.ts
Refactored `CognitoUserManagementPlugin`'s thrown errors to use the encapsulated error message.
Checklist:
> refactor(workbench-core/authentication): refactored error messages

- common/config/rush/pnpm-lock.yaml
- workbench-core/audit/tsconfig.json
- workbench-core/authorization/README.md
- workbench-core/authorization/config/jest.config.json
- workbench-core/authorization/package.json
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicPermissionsPluginInputs.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamoDBDynamicPermissionsPlugin.test.ts
- workbench-core/authorization/src/dynamicAuthorization/errors/errors.test.ts
- workbench-core/authorization/src/index.ts
- workbench-core/example/infrastructure/src/__tests__/__snapshots__/infrastructure-stack.test.ts.snap
- Dynamic Authorization Service Implemented
- Full test coverage for dynamic authorization
Checklist:
> feat: dynamic authorization service implemented

- common/changes/@aws/swb-app/maghirardelli-gali-1956-get-project-api_2022-11-02-20-03.json
- common/changes/@aws/workbench-core-accounts/maghirardelli-gali-1956-get-project-api_2022-11-02-20-03.json
- solutions/swb-app/src/projectRoutes.ts
- solutions/swb-app/src/schemas/projects/getProjectSchema.ts
- solutions/swb-app/src/staticRouteConfig.ts
- solutions/swb-reference/SWBv2.postman_collection.json
- workbench-core/accounts/README.md
- workbench-core/accounts/package.json
- workbench-core/accounts/src/index.ts
- workbench-core/accounts/src/models/getProjectRequest.ts
- workbench-core/accounts/src/services/projectService.test.ts
- workbench-core/accounts/src/services/projectService.ts
Issue #, if available: GALI-1956
update the Get Project method and add GET project API
Fixed various other bugs within Project Service scope
Integ tests to come
Checklist:
> feat: add GET project API

- common/changes/@aws/workbench-core-accounts/maghirardelli-push-common-code-from-proj-api-to-develop_2022-11-02-21-10.json
- common/changes/@aws/workbench-core-base/maghirardelli-push-common-code-from-proj-api-to-develop_2022-11-02-21-10.json
- common/changes/@aws/workbench-core-environments/maghirardelli-push-common-code-from-proj-api-to-develop_2022-11-02-21-10.json
- common/config/rush/pnpm-lock.yaml
- workbench-core/accounts/src/constants/hostingAccountStatus.ts
- workbench-core/base/README.md
- workbench-core/base/package.json
- workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
- workbench-core/base/src/aws/helpers/dynamoDB/getter.test.ts
- workbench-core/base/src/constants/queryParams.ts
- workbench-core/base/src/index.ts
- workbench-core/base/src/utilities/paginationHelper.test.ts
- workbench-core/base/src/utilities/paginationHelper.ts
- workbench-core/environments/README.md
- workbench-core/environments/src/services/environmentService.ts
- workbench-core/environments/src/services/environmentTypeConfigService.ts
- workbench-core/environments/src/services/environmentTypeService.ts
- workbench-core/example/infrastructure/src/__tests__/__snapshots__/example-stack.test.ts.snap
refactor utilities for pagination and dynamoDBService and services that consume them
add tests for DynamoDB
fix small typos
Checklist:
> fix(utilities): refactor utilities, add tests, typo fixes

- workbench-core/example/infrastructure/package.json
> chore: fix example package snapshot error and some cleanup

- common/changes/@aws/swb-app/sevu-features-delete-user-api_2022-11-09-16-01.json
- solutions/swb-app/src/staticPermissionsConfig.ts
- solutions/swb-app/src/staticRouteConfig.ts
- solutions/swb-app/src/userRoutes.ts
- solutions/swb-reference/SWBv2.postman_collection.json
- solutions/swb-reference/integration-tests/support/resources.ts
- solutions/swb-reference/integration-tests/support/resources/base/collectionResource.ts
- solutions/swb-reference/integration-tests/support/resources/base/resource.ts
- solutions/swb-reference/integration-tests/support/resources/users/user.ts
- solutions/swb-reference/integration-tests/support/resources/users/users.ts
- solutions/swb-reference/integration-tests/tests/isolated/users/delete.test.ts
- solutions/swb-reference/package.json
> feat: delete user api

- common/changes/@aws/workbench-core-authorization/sevu-tasks-mock-dynamic-auth_2022-11-15-18-25.json
- workbench-core/authorization/README.md
- workbench-core/authorization/src/errors/errors.test.ts
- workbench-core/authorization/src/errors/groupAlreadyExistsError.ts
- workbench-core/authorization/src/errors/groupNotFoundError.ts
- workbench-core/authorization/src/index.ts
- workbench-core/authorization/src/mockDynamicAuthorizationService.test.ts
- workbench-core/authorization/src/mockDynamicAuthorizationService.ts
- workbench-core/authorization/src/models/assignUserToGroup.ts
- workbench-core/authorization/src/models/createGroup.ts
- workbench-core/authorization/src/models/createIdentityPermissions.ts
- workbench-core/authorization/src/models/deleteGroup.ts
- workbench-core/authorization/src/models/deleteIdentityPermissions.ts
- workbench-core/authorization/src/models/deleteSubjectPermissions.ts
- workbench-core/authorization/src/models/dynamicPermissionsPlugin.ts
- workbench-core/authorization/src/models/getIdentityPermissionsByIdentity.ts
- workbench-core/authorization/src/models/getIdentityPermissionsBySubject.ts
- workbench-core/authorization/src/models/getUserGroups.ts
- workbench-core/authorization/src/models/getUsersFromGroup.ts
- workbench-core/authorization/src/models/identityPermission.ts
- workbench-core/authorization/src/models/permissionsService.ts
- workbench-core/authorization/src/models/removeUserFromGroup.ts
> chore: add mock dynamic authz service

- common/changes/@aws/swb-app/fix-zod-filter-sort-requests_2022-11-17-16-41.json
- common/changes/@aws/workbench-core-base/fix-zod-filter-sort-requests_2022-11-17-16-41.json
- common/config/rush/pnpm-lock.yaml
- solutions/swb-app/package.json
- solutions/swb-app/src/validatorHelper.ts
- workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.test.ts
- workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
- workbench-core/base/src/index.ts
- workbench-core/base/src/interfaces/filterRequest.ts
- workbench-core/base/src/interfaces/paginatedResponse.ts
- workbench-core/base/src/interfaces/queryNumberParamFilter.ts
- workbench-core/base/src/interfaces/queryParameterFilter.ts
- workbench-core/base/src/interfaces/queryStringParamFilter.ts
- workbench-core/base/src/schemas/queryParameterFilterSchema.ts
- workbench-core/base/src/utilities/queryParamsFiltersUtils.test.ts
feat: add common code for filter using Zod
[PR](https://github.com/aws-solutions/solution-spark-on-aws/pull/623) with implementation details for how to use these classes.
Checklist:
> feat: add common code for filter using Zod

- solutions/swb-app/src/projectRoutes.ts
- solutions/swb-app/src/staticPermissionsConfig.ts
- solutions/swb-app/src/staticRouteConfig.ts
- solutions/swb-reference/integration-tests/support/resources/projects/project.ts
- solutions/swb-reference/integration-tests/tests/isolated/projects/removeUserFromProject.test.ts
Issue #, if available: GALI-1762
Description of changes: remove user from project + negative tests
Checklist:
> feat: remove user from project

- common/changes/@aws/workbench-core-datasets/sevu-tasks-add-check-dependency-function_2022-11-23-20-40.json
- workbench-core/datasets/README.md
- workbench-core/datasets/src/dataSetService.test.ts
- workbench-core/datasets/src/dataSetService.ts
- workbench-core/example/app/src/routes/datasetRoutes.ts
Description of changes: add optional check dependency function to dataset service
Checklist:
> feat: add check dependency function to dataset service

- common/changes/@aws/swb-app/sevu-tasks-add-metadata-service-methods_2022-11-25-21-00.json
- common/changes/@aws/workbench-core-base/sevu-tasks-add-metadata-service-methods_2022-11-25-21-00.json
- solutions/swb-app/src/costCenterRoutes.ts
- solutions/swb-app/src/validatorHelper.ts
- solutions/swb-reference/src/backendAPI.ts
- workbench-core/base/README.md
- workbench-core/base/src/index.ts
- workbench-core/base/src/services/metadataService.test.ts
- workbench-core/base/src/services/metadataService.ts
- workbench-core/base/src/utilities/paginationHelper.ts
- workbench-core/base/src/utilities/validatorHelper.ts
> feat: added manage metadata methods to metadata service

- solutions/swb-app/src/projectRoutes.ts
- solutions/swb-app/src/staticRouteConfig.ts
- solutions/swb-reference/SWBv2.postman_collection.json
- solutions/swb-reference/integration-tests/support/resources/projects/project.ts
- solutions/swb-reference/integration-tests/tests/isolated/projects/listUsersForProject.test.ts
- workbench-core/base/README.md
- workbench-core/base/src/index.ts
- workbench-core/base/src/utilities/promiseUtils.test.ts
- workbench-core/base/src/utilities/promiseUtils.ts
- workbench-core/base/src/utilities/textUtil.ts
Issue #, if available: GALI-1932
Description of changes: list project users by role + negative tests.
Pending dynamic auth Z for other tests.
Checklist:
> feat: list users for project by role

- .github/workflows/merge-commit-topic-branch-pr-to-feat-branch.yml
test merge commits on feat/* branches
Checklist:
> chore: test merge commit from topic branch

- .github/workflows/merge-commit-topic-branch-pr-to-feat-branch.yml
> chore: cleanup

- common/changes/@aws/workbench-core-environments/sevu-features-post-deployment-script_2022-12-06-15-50.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- solutions/swb-reference/package.json
- solutions/swb-reference/src/postDeployment.ts
- workbench-core/environments/README.md
- workbench-core/environments/src/index.ts
- workbench-core/environments/src/postDeployment/authorizationSetup.test.ts
- workbench-core/environments/src/postDeployment/authorizationSetup.ts
Issue #, if available: GALI-1930
Description of changes: post deployment script using mock dynamic auth z implementation
Checklist:
> feat: Bootstrap IT Admin User

- common/changes/@aws/workbench-core-audit/fix-moveAuditLogger_2022-12-08-00-32.json
- common/changes/@aws/workbench-core-base/fix-moveAuditLogger_2022-12-08-00-32.json
- common/changes/@aws/workbench-core-environments/fix-moveAuditLogger_2022-12-08-00-32.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- solutions/swb-reference/src/backendAPI.ts
- workbench-core/audit/README.md
- workbench-core/audit/package.json
- workbench-core/audit/src/auditLogger.test.ts
- workbench-core/audit/src/auditLogger.ts
- workbench-core/audit/src/index.ts
- workbench-core/base/README.md
- workbench-core/base/package.json
- workbench-core/base/src/index.ts
- workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
- workbench-core/example/app/src/services/datasetService.ts
> fix: move AuditLogger into the Audit package

- solutions/swb-ui/infrastructure/src/hosting-infra/ecs-cluster.ts
* Removed unused EC2 instance from ECS cluster
* Added targeted autoscaling policy to FargateService to scale up when CPU util reaches 50%.
Checklist:
> feat(swb-ui): enable ECS Fargate Service autoscaling and remove EC2 instance

- workbench-core/authorization/README.md
- workbench-core/authorization/config/jest.config.json
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/addUserToGroup.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/createGroup.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/createIdentityPermissions.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/deleteGroup.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/deleteIdentityPermissions.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/doesGroupExist.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/dynamicOperation.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getGroupUsers.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getIdentityPermissionsBySubject.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getUserGroups.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/identityPermission.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/init.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isAuthorizedOnRoute.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isAuthorizedOnSubject.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isRouteIgnored.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isRouteProtected.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isUserAssignedToGroup.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/removeUserFromGroup.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
- workbench-core/base/README.md
Dynamic authorization service stub added along with request and response interfaces.
Checklist:
> feat: dynamic authorization service interfaces added

- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getDynamicOperationsByRoute.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getIdentityPermissionsByIdentity.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationPermissionsPlugin.ts
> feat: dynamic authorization permissions plugin interfaces

- solutions/swb-reference/integration-tests/config/example.yaml
- solutions/swb-reference/integration-tests/config/testEnv.yaml
- solutions/swb-reference/integration-tests/support/setup.ts
- solutions/swb-reference/integration-tests/support/utils/settings.ts
I failed to verify that the last fix was sufficient. I've tested the entire Account multistep integration flow to verify that everything now passes.
Checklist:
> chore: integration test hosting acount handler role arn update part 2

- solutions/swb-reference/src/config/demo.yaml
We need to add a config update for demo.yaml just like we did in [testEnv.yaml](https://github.com/aws-solutions/solution-spark-on-aws/blob/develop/solutions/swb-reference/src/config/testEnv.yaml). This fixes the fail demo deployment [here](https://github.com/aws-solutions/solution-spark-on-aws/actions/runs/3715445764/jobs/6301496858)
Checklist:
> chore: update demo.yaml with fieldsToMaskWhenAuditing

- common/changes/@aws/workbench-core-authorization/topic-implement-get-set-group-status_2022-12-16-20-22.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- workbench-core/authorization/README.md
- workbench-core/authorization/config/jest.config.json
- workbench-core/authorization/package.json
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getGroupStatus.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/setGroupStatus.ts
- workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
- workbench-core/authorization/src/dynamicAuthorization/groupStatus.ts
- workbench-core/authorization/src/dynamicAuthorization/models/GroupMetadata.ts
- workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
- workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
- workbench-core/authorization/src/errors/errors.test.ts
- workbench-core/authorization/src/errors/tooManyRequestsError.ts
- workbench-core/authorization/src/index.ts
- implemented `getGroupStatus()` in `wbcGroupManagementPlugin`
- implemented `setGroupStatus()` in `wbcGroupManagementPlugin`
- removed `doesGroupExist` from `GroupManagementPlugin` interface
Checklist:
> feat: implement getGroupStatus and setGroupStatus

- solutions/swb-reference/src/proxyHandlerLambda.ts
GALI-2019
Updating proxy lambda to handle both pure API calls and UI requests.
Checklist:
> feat: proxy lambda updates

- common/changes/@aws/workbench-core-base/atmikev-GALI-2124_DataSetWithEnvironment_2022-12-20-18-23.json
- common/changes/@aws/workbench-core-environments/atmikev-GALI-2124_DataSetWithEnvironment_2022-12-20-18-23.json
- solutions/swb-reference/src/backendAPI.ts
- solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentLifecycleService.test.ts
- solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentLifecycleService.ts
- workbench-core/base/README.md
- workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
- workbench-core/environments/README.md
- workbench-core/environments/src/handlers/statusHandler.test.ts
- workbench-core/environments/src/handlers/statusHandler.ts
- workbench-core/environments/src/services/environmentService.test.ts
- workbench-core/environments/src/services/environmentService.ts
- workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
GALI-2124
Create a `DataSet With Environment` item on environment creation.
> feat: [GALI-2124] data set with environment

- workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
- workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/group.test.ts
Integration test fix.
Checklist:
> fix: add user to group integration test

- .github/workflows/deploy-integration-swb-reference-byon.yml
- .github/workflows/merge-develop-to-stage.yml
- .gitignore
- solutions/swb-reference/src/config/swbv2-private.yaml
- solutions/swb-reference/src/config/testEnv.yaml
- solutions/swb-ui/infrastructure/src/hosting-infra/ecs-cluster.ts
- solutions/swb-ui/ui/README.md
- solutions/swb-ui/ui/scripts/deploy.sh
GALI-1859
Set up GitHub workflow for BYON e2etest pipeline.
Checklist:
> chore: create GH workflow for BYON pipeline

- common/changes/@aws/workbench-core-authorization/topic-getIdentityPermissionsBySubject_2023-01-05-08-28.json
- workbench-core/authorization/README.md
- workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
- workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getIdentityPermissionsBySubject.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
- workbench-core/authorization/src/index.ts
- workbench-core/example/app/src/configs/staticRouteConfig.ts
- workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
- workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermissions.ts
- workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
> feat: getIdentityPermissionsBySubject implemented

- workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermissions.ts
- workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
> fix: permissions collision for integration test

- common/changes/@aws/workbench-core-authorization/topic-verify-group-status-for-addUserToGroup_2023-01-05-19-00.json
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
- workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
- workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
- workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
Issue #, if available: MAFoundation-577
Verification of group status when performing addUserToGroup
Checklist:
> feat: verify group status for addUserToGroup

- common/changes/@aws/workbench-core-authorization/topic-deleteIdentityPermissions_2023-01-06-12-26.json
- workbench-core/authorization/README.md
- workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
- workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/createIdentityPermissions.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/deleteIdentityPermissions.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/identityPermission.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
- workbench-core/authorization/src/errors/errors.test.ts
- workbench-core/authorization/src/errors/retryError.ts
- workbench-core/authorization/src/index.ts
- workbench-core/example/app/src/configs/staticPermissionsConfig.ts
- workbench-core/example/app/src/configs/staticRouteConfig.ts
- workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
- workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermissions.ts
- workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
> feat: deleteIdentityPermissions implemented

- solutions/example-ui-app/package.json
- solutions/swb-ui/ui/package.json
1. Disable telemetry for nextjs project builds
Checklist:
> chore: disable telemetry for nextjs project builds

- common/changes/@aws/workbench-core-base/maghirardelli-gali-1925-integ-tests_2023-01-10-17-51.json
- solutions/swb-reference/README.md
- solutions/swb-reference/integration-tests/config/example.yaml
- solutions/swb-reference/integration-tests/config/testEnv.yaml
- solutions/swb-reference/integration-tests/support/resources.ts
- solutions/swb-reference/integration-tests/support/resources/projects/project.ts
- solutions/swb-reference/integration-tests/support/resources/projects/projects.ts
- solutions/swb-reference/integration-tests/support/utils/settings.ts
- solutions/swb-reference/integration-tests/tests/isolated/projects/create.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projects/softDelete.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projects/update.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/project.test.ts
- workbench-core/base/README.md
- workbench-core/base/src/aws/helpers/dynamoDB/updater.test.ts
- workbench-core/base/src/aws/helpers/dynamoDB/updater.ts
Issue #, if available: GALI-1925
added integration testing (negative and multi-step) for project APIs
found a bug with `updater.ts` code during testing. Fixed it, and wrote unit tests to cover the change
Checklist:
> test(projects): integ tests

- solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookLaunchSSM.yaml
- solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookTerminateSSM.yaml
Issue #, if available: GALI-1687
Add description to SSM documents that provide complete details on inputs, outputs, and actions taken.
Checklist:
* [ * ] Have you successfully deployed to an AWS account with your changes?
> docs: improve ssm document

- solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebook.cfn.yaml
Issue #, if available:GALI-1698
Checklist:
> docs: add securitygroup description

- solutions/swb-ui/ui/end-to-end-tests/cypress/support/common-utils.ts
- solutions/swb-ui/ui/end-to-end-tests/cypress/support/environments-utils.ts
Hide multi select studies so e2e can keep going with test
Checklist:
> fix(e2e environment): fix issue with studies blocking clicking ETC

- .viperlightignore
- common/changes/@aws/swb-app/topic-datasets-getAllAccess_2023-01-12-00-51.json
- common/changes/@aws/workbench-core-datasets/topic-datasets-getAllAccess_2023-01-12-00-51.json
- solutions/swb-app/src/dataSets/getAccessPermissionRequestParser.ts
- workbench-core/datasets/README.md
- workbench-core/datasets/src/dataSetService.test.ts
- workbench-core/datasets/src/dataSetService.ts
- workbench-core/datasets/src/dataSetsAuthorizationPlugin.ts
- workbench-core/datasets/src/models/getAccessPermissionRequest.ts
- workbench-core/datasets/src/schemas/createExternalEndpoint.ts
- workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.test.ts
- workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.ts
- workbench-core/example/app/src/configs/staticPermissionsConfig.ts
- workbench-core/example/app/src/configs/staticRouteConfig.ts
- workbench-core/example/app/src/routes/datasetRoutes.ts
- workbench-core/example/infrastructure/integration-tests/support/resources/datasets/dataset.ts
- workbench-core/example/infrastructure/integration-tests/tests/datasets/accessPermissions.test.ts
- workbench-core/example/infrastructure/integration-tests/tests/datasets/delete.test.ts
Checklist:
* [ X ] Have you successfully deployed to an AWS account with your changes?
* [ X ] Have you written new tests for your core changes, as applicable?
> feat(datasets): implement getDataSetsAccessPermissions and getAllDataSetsAccessPermissions

- solutions/swb-ui/ui/end-to-end-tests/config/testEnv.yaml
update the project name for e2e test usage since I deleted the defunct project. I also manually updated the Dynamic Authorization record to allow the e2e test to use this project and dataset in the config file
Checklist:
> test(e2e tests): update project name for e2e tests

- .github/CODEOWNERS
1. Update CODEOWNERS
Checklist:
> chore: ma-foundation-600: update CODEOWNERS

- common/changes/@aws/workbench-core-authorization/topic-dynamicAuthzDeleteSubjectIdentityPermissions_2023-01-19-17-17.json
- workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
- workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/deleteSubjectIdentityPermissions.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationPermissionsPlugin.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
- workbench-core/example/app/src/configs/staticRouteConfig.ts
- workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
- workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermissions.ts
- workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
Issue #, if available: MAFoundation-584
Checklist:
> feat: dynamic authz - implement deleteSubjectIdentityPermissions

- workbench-core/example/infrastructure/integration-tests/tests/datasets/get.test.ts
- fixed broken tests
Checklist:
> fix: fixed broken tests

- .github/workflows/merge-develop-to-stage.yml
> fix: spelling issue with deploy-swb-reference-byon

- .github/workflows/deploy-integration-swb-reference.yml
- .github/workflows/deploy-swb-reference-demo.yml
- solutions/swb-reference/src/config/demo.yaml
- solutions/swb-reference/src/config/example.yaml
- solutions/swb-reference/src/config/testEnv.yaml
* Added domainName and hostedZoneId to testEnv config
* Added domainName and hostedZoneId to demo config
* Fixed typo in example.yaml
* 
Checklist:
> fix: add domainName and hostedZoneId to testEnv and demo configs

- common/config/rush/pnpm-config.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
> fix: update jszip due to vulnerability

- common/config/rush/pnpm-config.json
- common/config/rush/repo-state.json
- solutions/swb-reference/src/proxyHandlerLambda.ts
- solutions/swb-ui/infrastructure/src/hosting-infra/ecs-cluster.ts
Axios calls in proxy lambda rejecting due to cookies being undefined.
Updated axios calls in proxy lambda to remove undefined headers.
Checklist:
> fix: proxy lambda headers fix

- solutions/swb-ui/ui/end-to-end-tests/config/testEnv.yaml
- solutions/swb-ui/ui/end-to-end-tests/cypress/support/commands.ts
-fix e2e path issue
-remove studies from e2e as there are no studies in test env
Checklist:
> fix(swb ui): fix e2e issue with path and remove studies from e2e test

- .github/workflows/merge-develop-to-stage.yml
- solutions/swb-reference/integration-tests/support/setup.ts
- solutions/swb-ui/ui/end-to-end-tests/cypress/integration/common/environments.cy.ts
- solutions/swb-ui/ui/end-to-end-tests/cypress/integration/common/login.cy.ts
Fix for flaky tests in pipeline.
Adding 1 retry attempt to integration tests and 2 for Cypress tests (since UI is dependent on ECS tasks being up).
Checklist:
> fix: test retry attempts

- solutions/swb-ui/ui/end-to-end-tests/cypress/support/environments-utils.ts
N/A
Add trailing slash for env list page visit
Checklist:
> fix: env list cypress

- .github/workflows/enable-feat-protection.yml
- .github/workflows/feat-deletion.yml
- .github/workflows/no-response.yml
- .github/workflows/pipeline-workflow.yml
1. Update all workflows to use `ubuntu-20.04`
Checklist:
> ci: update all workflows to use ubuntu-20.04

- solutions/swb-reference/integration-tests/config/testEnv.yaml
* Updated project used for swb-reference integ tests in order to make sure Cognito groups exist for it
* Verified Cognito groups exist for proj-8b0d7813-bd0c-41f3-80e6-67129a3d7460#ProjectAdmin and proj-8b0d7813-bd0c-41f3-80e6-67129a3d7460#Researcher
> fix: updating project used for integ tests

- solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/create.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/update.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/delete.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/get.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/list.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/listProjects.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts
-Randomize multistep id of ET in et-etc integ tests
-Make sure negative tests do not point to previously created ET that failed to delete 
Checklist:
> chore: fix ETC integ test

- common/changes/@aws/workbench-core-authorization/topic-implementDynamicAuthzMiddleware_2023-02-17-05-52.json
- solutions/example-ui-app/cache/config.json
- workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
- workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationMiddleware.test.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationMiddleware.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
- workbench-core/authorization/src/dynamicAuthorization/models/getDynamicOperationsByRoute.ts
- workbench-core/authorization/src/index.ts
- workbench-core/example/app/src/configs/dynamicRouteConfig.ts
- workbench-core/example/app/src/configs/dynamicRoutesIgnored.ts
- workbench-core/example/app/src/generateRouter.ts
- workbench-core/example/app/src/routes/auditRoutes.ts
- workbench-core/example/app/src/routes/sampleRoutes.ts
- workbench-core/example/app/src/routes/staticAuthorizationRoutes.ts
> feat: implement dynamic authz middleware

- rush.json
> chore: rush node version update

- common/changes/@aws/workbench-core-infrastructure/janeyu-cognito-access_2023-02-20-20-35.json
- workbench-core/infrastructure/src/workbenchCognito.test.ts
- workbench-core/infrastructure/src/workbenchCognito.ts
> feat: add 'ALLOW_USER_PASSWORD_AUTH' cognito

- .github/workflows/deploy-integration-swb-reference.yml
> ci: fix JavaScript heap out of memory

- solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
- fixed comparer function in datasets multistep integ test
Checklist:
> test: datasets integ test fix

- common/changes/@aws/swb-app/topic-addAvailableDeletedStatusToEtc_2023-02-21-22-07.json
- common/changes/@aws/workbench-core-environments/topic-addAvailableDeletedStatusToEtc_2023-02-21-22-07.json
- solutions/swb-app/src/envTypeConfigs/environmentTypeConfig.ts
- workbench-core/environments/src/constants/environmentTypeConfigStatus.ts
- workbench-core/environments/src/models/environmentTypeConfigs/environmentTypeConfig.ts
- workbench-core/environments/src/services/environmentTypeConfigService.test.ts
- workbench-core/environments/src/services/environmentTypeConfigService.ts
- workbench-core/environments/src/services/environmentTypeService.test.ts
Issue #, if available: GALI-2284
Checklist:
> feat: Add AVAILABLE/DELETED status to environmentTypeConfig

- solutions/swb-reference/integration-tests/support/complex/paabHelper.ts
- solutions/swb-reference/integration-tests/tests/isolated/sshKeys/listUserSshKeysForProject.test.ts
push updated PaaB helper for integ tests to develop
Checklist:
> fix(integ tests): Update paab helper to develop

- .github/workflows/merge-develop-to-stage.yml
- solutions/swb-reference/integration-tests/tests/isolated/sshKeys/listUserSshKeysForProject.test.ts
- solutions/swb-reference/src/SWBStack.ts
GALI-2257
Adding GitHub workflow for BYON use case
Checklist:
> chore: add BYON GH workflow

- .github/workflows/merge-develop-to-stage.yml
N/A
Removing BYON deployment dependency from workflow temporarily.
Checklist:
> fix: remove dependency on BYON workflow

- .github/workflows/merge-develop-to-stage.yml
N/A
Disabling BYON deploy step in pipeline. Investigating root cause for CDK synth failure.
Checklist:
> fix: remove BYON workflow step

- common/changes/@aws/swb-app/farandac-standardize-delete-requests_2023-02-23-03-19.json
- solutions/swb-app/src/costCenterRoutes.ts
- solutions/swb-app/src/dataSetRoutes.ts
- solutions/swb-app/src/projectRoutes.ts
- solutions/swb-app/src/sshKeyRoutes.ts
- solutions/swb-app/src/staticPermissionsConfig.ts
- solutions/swb-app/src/staticRouteConfig.ts
- solutions/swb-app/src/userRoutes.ts
- solutions/swb-reference/SWBv2.postman_collection.json
- solutions/swb-reference/integration-tests/support/resources/base/resource.ts
- solutions/swb-reference/integration-tests/support/resources/costCenters/costCenter.ts
- solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
- solutions/swb-reference/integration-tests/support/resources/projects/project.ts
- solutions/swb-reference/integration-tests/support/resources/users/user.ts
- solutions/swb-reference/integration-tests/tests/isolated/costCenter/softDelete.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projects/create.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projects/softDelete.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/sshKeys/delete.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/users/delete.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/costCenter.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/project.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/userApi.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/userProject.test.ts
CHAM-216
-Remove /softDelete from 
- Cost Center
-Projects
-DataSets
-Add /purge to:
-Users
-SshKeys
-Update Integ tests to reflect changes
Checklist:
> chore(api delete requests): standardize soft-delete and hard-delete Routes

- solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebook.cfn.yaml
GALI-2167
Contains autostop command fix similar to this SWBv1 [PR](https://github.com/awslabs/service-workbench-on-aws/pull/1129)
Checklist:
> fix: update SM autostop command for AL2

- solutions/swb-reference/src/dynamicRouteConfig.ts
Update permissions in dynamic routes for
-CostCenter
-Project
-Users
Checklist:
> fix: Update delete permissions

- common/changes/@aws/swb-app/fix-listEnvTypeConfig_2023-02-23-23-45.json
- solutions/swb-app/src/environmentTypeConfigRoutes.ts
> fix: list env type config should be using req.query

- solutions/swb-reference/integration-tests/tests/isolated/sshKeys/create.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/sshKeys/delete.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/sshKeys/listUserSshKeysForProject.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/sshKeys.test.ts
> fix(ssh-integ-test): move expect to beforeEach

- solutions/swb-reference/src/templates/new-firewall-vpc.yaml
- solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
GALI-2277
- Remove hardcoded AZs from firewall template
Checklist:
> fix: replace harcoded AZs for firewall

- common/changes/@aws/swb-app/atmikev-paab-dataset-integration-tests_2023-02-25-00-36.json
- common/changes/@aws/workbench-core-accounts/atmikev-paab-dataset-integration-tests_2023-02-25-00-36.json
- common/changes/@aws/workbench-core-datasets/atmikev-paab-dataset-integration-tests_2023-02-25-00-36.json
- common/changes/@aws/workbench-core-environments/atmikev-paab-dataset-integration-tests_2023-02-25-00-36.json
- solutions/swb-app/src/dataSetRoutes.ts
- solutions/swb-app/src/dataSets/dataSetPlugin.ts
- solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
- solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
- solutions/swb-reference/src/dynamicRouteConfig.ts
- solutions/swb-reference/src/services/dataSetService.test.ts
- solutions/swb-reference/src/services/dataSetService.ts
> chore: Project as a Boundary dataset integration tests

- solutions/swb-reference/integration-tests/config/swbv2-private.yaml
* Re-onboarded hosting account to fix issues with status handler
Checklist:
> chore: update account id used for byon integ tests

- common/changes/@aws/workbench-core-environments/farandac-fix-listEnvs-paab_2023-03-02-17-45.json
- solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
- workbench-core/environments/README.md
- workbench-core/environments/src/services/environmentService.test.ts
- workbench-core/environments/src/services/environmentService.ts
CHAM-224
-fix issue where non-admins will only see their own environmetns
Checklist:
> fix: allow other users in same project to see environments

- solutions/swb-reference/src/services/dataSetService.test.ts
> chore: remove unnecessary log

- solutions/swb-reference/src/postDeployment/authorizationSetup.ts
> fix: test fix

- common/changes/@aws/swb-app/farandac-add-Zod-to-UserProj_2023-03-08-20-33.json
- solutions/swb-app/README.md
- solutions/swb-app/src/projectRoutes.ts
- solutions/swb-app/src/projects/disassociateProjectUserRequest.ts
- solutions/swb-app/src/projects/disassociateUserFromProjectRequest.ts
GALI-2313
Add zod to disassociate user from proj
Checklist:
> chore(project routes): add zod to disassociate user to proj

- README.md
- common/changes/@aws/swb-app/kevpark-update-postman_2023-03-13-09-15.json
- solutions/swb-app/README.md
- solutions/swb-app/config/jest.config.json
- solutions/swb-app/src/dataSetRoutes.ts
- solutions/swb-reference/README.md
- solutions/swb-reference/SWBv2.postman_collection.json
1. Rebase release da93c65 to develop
Checklist:
> chore: rebase release da93c65 to develop

- README.md
- solutions/swb-reference/README.md
- solutions/swb-reference/integration-tests/support/resources/sshKeys/sshKey.ts
- solutions/swb-reference/integration-tests/tests/isolated/sshKeys/create.test.ts
1. Rebase release aa56a8d to develop
Checklist:
> chore: rebase release aa56a8d to develop

- .github/workflows/readme-commit.yml
- .github/workflows/verify-changefiles.yml
1. Fix changefiles workflow
Checklist:
> chore: fix github workflow

- solutions/swb-reference/src/SWBStack.ts
- solutions/swb-reference/src/infra/SWBVpc.ts
https://sim.amazon.com/issues/GALI-2107
Checklist:
> fix(appSec): set CWL Retention Period to 10 years

- common/changes/@aws/workbench-core-environments/fix-cognito-pool-id-retrieval_2023-03-21-20-19.json
- solutions/swb-reference/src/postDeployment.ts
- workbench-core/environments/README.md
- workbench-core/environments/src/postDeployment/cognitoSetup.test.ts
- workbench-core/environments/src/postDeployment/cognitoSetup.ts
N/A
Pass stack name to CognitoSetup directly, rather than extracting it from user pool name.
Checklist:
> fix: cognito pool id retrieval

- .github/workflows/deploy-integration-example-app.yml
1. example app deployment/integration-test fix
Checklist:
> ci: example app deployment/integration-test fix

- solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebook.cfn.yaml
- solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml
- solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
- solutions/swb-reference/src/templates/onboard-account.cfn.yaml
GALI-2315
suppress cfn-nag warning identified in .cfn.yaml
> chore(cfn-nag): suppress .cfn.yaml files

- solutions/swb-reference/README_SOLUTIONS.md
- solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.ts
GALI-2408
Add manual steps for ALB access logging in Solutions deployment.
Checklist:
> docs: instructions for ALB access log in solutions

- solutions/swb-reference/README_SOLUTIONS.md
- solutions/swb-reference/src/config/example.yaml
- solutions/swb-reference/src/templates/new-firewall-vpc.yaml
- solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
N/A
Cleanup resources in the firewall and TGW onboarding templates.
Checklist:
> chore: firewall and TGW template cleanup

- .github/workflows/deploy-integration-swb-reference-byon.yml
Issue #, if available: V873711415
Remove unnecessary secrets in the config values of the workflow
Checklist:
> chore(gh actions): remove unnecessary workflow config values

- common/config/rush/pnpm-config.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
1. `xml2js` pnpm audit fix
Checklist:
> chore: xml2js pnpm audit fix

- .github/workflows/create-release-pr-to-develop.yml
- common/config/rush/repo-state.json
> feat: automate merge release to develop

- solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
update integ tests for datasets
Checklist:
> test(dataset integ test): update dataset integ tests

- common/changes/@aws/workbench-core-infrastructure/fix-s3-object-ownership_2023-04-12-19-28.json
- solutions/swb-reference/src/SWBStack.ts
- solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.test.ts
- workbench-core/example/infrastructure/src/example-stack.ts
- workbench-core/infrastructure/src/workbenchSecureS3Bucket.test.ts
- workbench-core/infrastructure/src/workbenchSecureS3Bucket.ts
1. Fix s3 bucket object ownership
Checklist:
> chore: fix s3 bucket object ownership

- sonar-project.properties
N/A
Update SonarQube configuration to skip build files.
Checklist:
> fix: sonarqube config

- .github/workflows/automerge-release-pr-to-develop.yml
- .github/workflows/create-release-pr-to-develop.yml
> feat: add automerge labeler

- .github/workflows/create-release-pr-to-develop.yml
> fix: remove preference for release

- .github/workflows/create-release-pr-to-develop.yml
> fix: remove checkout ours

- solutions/swb-reference/SWBv2.openapi.json
- solutions/swb-reference/SWBv2.postman_collection.json
> feat: add OpenAPI collection for swb-reference

- .github/workflows/create-release-pr-to-develop.yml
> fix: reorder create-release-pr-to-develop workflow

- .github/workflows/automerge-release-pr-to-develop.yml
> fix: label name

- common/changes/@aws/workbench-core-accounts/fix-aws-cdk-iam_2023-04-13-17-40.json
- common/changes/@aws/workbench-core-datasets/fix-aws-cdk-iam_2023-04-13-17-40.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- solutions/swb-reference/integration-tests/support/complex/accountHelper.ts
- solutions/swb-reference/package.json
- workbench-core/accounts/package.json
- workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
- workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
- workbench-core/datasets/package.json
- workbench-core/datasets/src/awsUtilities/iamHelper.test.ts
- workbench-core/datasets/src/awsUtilities/iamHelper.ts
- workbench-core/datasets/src/s3DataSetStoragePlugin.ts
N/A
Use aws-cdk-lib for iam module.
Checklist:
> fix: aws cdk iam

- solutions/swb-reference/scripts/buildLambda.js
- workbench-core/example/infrastructure/scripts/generateCognitoTokens.js
N/A
Fix random code smells.
Checklist:
> fix: code smell

- solutions/swb-reference/src/SWBStack.ts
* Making SageMaker IAM policy use Pascal casing due to permission issues
Checklist:
> fix(swb-ref): adjust sagemaker iam policy

- sonar-project.properties
N/A
Excluding tsconfig file scans for sonarqube.
Checklist:
> fix: sonar exclusions

- sonar-project.properties
N/A
Testing sonar properties update
Checklist:
> fix: add sonar exclusions

- .viperlightignore
- common/changes/@aws/workbench-core-authorization/topic-dAuthzRateLimiter_2023-04-20-23-21.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- workbench-core/authorization/package.json
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationMiddleware.test.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationMiddleware.ts
- workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
> feat: enable rate limiter in dynamic authz middleware

- common/changes/@aws/swb-app/farandac-project-etc-input-validations_2023-04-24-03-01.json
- common/changes/@aws/workbench-core-authorization/farandac-project-etc-input-validations_2023-04-24-03-01.json
- common/changes/@aws/workbench-core-base/farandac-project-etc-input-validations_2023-04-24-03-01.json
- solutions/swb-app/src/projectEnvTypeConfigs/associateProjectEnvTypeConfigRequest.ts
- solutions/swb-app/src/projectEnvTypeConfigs/disassociateProjectEnvTypeConfigRequest.ts
- solutions/swb-app/src/projectEnvTypeConfigs/getProjectEnvTypeConfigRequest.ts
- solutions/swb-app/src/projectEnvTypeConfigs/listEnvTypeConfigProjectsRequest.ts
- solutions/swb-app/src/projectEnvTypeConfigs/listProjectEnvTypeConfigsRequest.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/delete.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/get.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/list.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/listProjects.test.ts
- solutions/swb-reference/src/services/dataSetService.test.ts
- solutions/swb-reference/src/services/projectEnvService.test.ts
- solutions/swb-reference/src/services/projectEnvTypeConfigService.test.ts
- solutions/swb-reference/src/services/swbProjectService.test.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationMiddleware.test.ts
- workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
- workbench-core/authorization/src/models/authenticatedUser.ts
- workbench-core/base/src/utilities/textUtil.ts
- workbench-core/base/src/utilities/validatorHelper.test.ts
- workbench-core/base/src/utilities/validatorHelper.ts
GALI-2323
Add length validations to project-etc routes
Add character validations to project-etc routes
Add require validations to project-etc routes
Update integ-tests for project-etc routes
Update unit tests for project-etc routes
Checklist:
> chore(project-etc routes): add format,length and required validations

- common/changes/@aws/workbench-core-authorization/farandac-authUser-fix-validation_2023-04-24-18-47.json
- workbench-core/authorization/src/models/authenticatedUser.ts
fix auth user input validation
Checklist:
> chore: auth user fix validation

- deployment/solution_config
GALI-2411
Updating product name in solution config.
Checklist:
> chore: update solution config

- common/changes/@aws/swb-app/chore-zod-update-projectenv_2023-05-04-15-18.json
- common/changes/@aws/workbench-core-base/chore-zod-update-projectenv_2023-05-04-15-18.json
- common/changes/@aws/workbench-core-environments/chore-zod-update-projectenv_2023-05-04-15-18.json
- solutions/swb-app/config/jest.config.json
- solutions/swb-app/src/envTypeConfigs/createEnvironmentTypeConfigRequest.ts
- solutions/swb-app/src/environmentTypeConfigRoutes.ts
- solutions/swb-app/src/projectEnvironmentRoutes.ts
- solutions/swb-app/src/projectEnvs/connectEnvironmentRequest.ts
- solutions/swb-app/src/projectEnvs/createEnvironmentRequest.ts
- solutions/swb-app/src/projectEnvs/getEnvironmentRequest.ts
- solutions/swb-app/src/projectEnvs/listProjectEnvironmentsRequest.ts
- solutions/swb-app/src/projectEnvs/startEnvironmentRequest.ts
- solutions/swb-app/src/projectEnvs/stopEnvironmentRequest.ts
- solutions/swb-app/src/projectEnvs/terminateEnvironmentRequest.ts
- solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/create.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/update.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/environments/launch.test.ts
- workbench-core/base/src/utilities/textUtil.test.ts
- workbench-core/base/src/utilities/textUtil.ts
- workbench-core/base/src/utilities/validatorHelper.ts
- workbench-core/environments/src/models/environmentTypeConfigs/createEnvironmentTypeConfigRequest.ts
GALI-2322
Adding zod validations for projectEnv routes.
Adding integ tests for projectEnv and ETC.
Checklist:
> chore: zod update projectenv

- common/changes/@aws/workbench-core-base/janeyu-metrics_2023-05-03-16-41.json
- solutions/swb-reference/src/SWBStack.ts
- solutions/swb-reference/src/accountHandlerLambda.ts
- solutions/swb-reference/src/backendAPI.ts
- solutions/swb-reference/src/constants.ts
- solutions/swb-reference/src/index.ts
- solutions/swb-reference/src/postDeployment.ts
- workbench-core/base/src/aws/awsService.ts
Issue #, if available:GALI-2359
* add user agent header to aws client
Checklist:
> chore(user-agent): add user agent

- solutions/swb-reference/README.md
- solutions/swb-reference/SWBv2.postman_collection.json
chore(docs update): minor updates for readme and postman collection
Checklist:
> chore(docs update): minor updates for readme and postman collection

- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/environment.test.ts
* Input validation changes broke tests that had spaces in resource names; those tests have been updated to remove spaces
Checklist:
> fix(swb-ref): update integ tests impacted by zod

- .github/CODEOWNERS
1. CODEOWNERS file update
Checklist:
> ci: codeowners update

- solutions/swb-reference/integration-tests/tests/isolated/users/createUser.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/users/updateUser.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
https://github.com/aws-solutions/solution-spark-on-aws/actions/runs/4950432667/jobs/8854039268
Fixing user integ test failures in GitHub integration test pipeline.
Checklist:
> fix: user integ tests

- common/changes/@aws/swb-app/janeyu-APIStatus_2023-05-11-18-33.json
- common/changes/@aws/workbench-core-accounts/janeyu-APIStatus_2023-05-11-18-33.json
- common/changes/@aws/workbench-core-base/janeyu-APIStatus_2023-05-11-18-33.json
- solutions/swb-app/src/environments/listEnvironmentsRequest.ts
- solutions/swb-reference/integration-tests/tests/isolated/costCenter/list.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projects/list.test.ts
- solutions/swb-reference/package.json
- workbench-core/accounts/src/models/costCenters/listCostCentersRequest.ts
- workbench-core/accounts/src/models/projects/listProjectsRequest.ts
- workbench-core/base/src/interfaces/queryStringParamFilter.ts
Issue #, if available: issues/P88136620
* add zod parser to filter name so empty name result in 400 bad request
* update integ test
Checklist:
> chore(zod): list empty name in filter status code 500 to 400

- buildspec.yml
- common/changes/@aws/workbench-core-infrastructure/node-version-update_2023-05-12-21-28.json
- rush.json
- workbench-core/infrastructure/src/workbenchDynamodb.test.ts
1. update CodeBuild and rush to >=node18
Checklist:
> chore: update CodeBuild and rush to >=node18

- .github/workflows/integration-tests-release.yml
- .github/workflows/merge-develop-to-stage.yml
> fix: remove deployment of example app from pipeline

- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- solutions/swb-reference/integration-tests/tests/isolated/users/createUser.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/users/updateUser.test.ts
- solutions/swb-reference/package.json
Fix updateUser and createUser integ tests with correct error messages
Checklist:
> test: fix user integ tests with right error message

- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- solutions/swb-reference/package.json
fix the integration test command to be the entire test suite
Checklist:
> fix: fix integration test command

- common/changes/@aws/workbench-core-user-management/janeyu-cognitoLimit_2023-05-12-23-46.json
- workbench-core/user-management/src/errors/errors.test.ts
- workbench-core/user-management/src/errors/userRolesExceedLimitError.ts
- workbench-core/user-management/src/index.ts
- workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts
- workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
Reverts aws-solutions/research-service-workbench-on-aws#1064
> revert(revert chore user-management): add cognito group limit 25

- solutions/swb-reference/integration-tests/config/release-candidate-private.yaml
- solutions/swb-reference/integration-tests/config/release-candidate.yaml
1. Fix integration test
Checklist:
> chore: fix integration test

- solutions/swb-reference/README.md
* minor updates to README for install and integration tests setup 
Checklist:
> docs: minor updates to README for install 

- solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
- solutions/swb-reference/src/templates/onboard-account.cfn.yaml
update solutionName in onboarding template
> chore(rename): update solutionName in onboard hosting template

- common/changes/@aws/workbench-core-user-management/maghirardelli-fix-list-user-integ-test_2023-05-26-23-36.json
- solutions/swb-reference/integration-tests/tests/isolated/users/listUsers.test.ts
- workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
have the proper error for negative integ test
Checklist:
> test: proper test error

- .github/workflows/deploy-integration-swb-reference-byon.yml
> fix: increase byon integ test workflow memory

- solutions/swb-reference/integration-tests/tests/isolated/costCenter/update.test.ts
chore: update cost center integ test error message
Checklist:
> chore: update cost center integ test error message

- README.md
update main README to include solution intro and collection metrics
> docs(readme): update main readme

- solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
N/A
Fix paab constructor call in list env test
Checklist:
> fix: update list env test paab constructor

- solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/get.test.ts
- solutions/swb-reference/package.json
> test: additional tests for aws account endpoint

- solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/list.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/environments/launch.test.ts
> test: add AuthZ test for create environment 

- solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
N/A
Adding integ test cases for PAAB
Checklist:
> chore: adding integ test cases for PAAB

- solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/delete.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/get.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/update.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/delete.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/get.test.ts
- solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts
Added ET and ETC negative tests for Researchers, PA, and Admin
* ET
* Get
* ITAdmin
* Added [link](https://github.com/aws-solutions/research-service-workbench-on-aws/blob/ba2c2f28ca0863b08f4aa49db9bdeb5fa7da42a1/solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts#L73)
* Proj Admin [link](https://github.com/aws-solutions/research-service-workbench-on-aws/blob/ba2c2f28ca0863b08f4aa49db9bdeb5fa7da42a1/solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts#L196)
* Added
* Researcher [link](https://github.com/aws-solutions/research-service-workbench-on-aws/blob/ba2c2f28ca0863b08f4aa49db9bdeb5fa7da42a1/solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts#L235)
* Added
* List
* ITAdmin
* …
> test: add getEnvironmentType as PA and Researcher

- solutions/swb-reference/integration-tests/tests/isolated/datasets/associate.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/datasets/permissions.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/datasets/remove.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/datasets/uploadFile.test.ts
- solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
> test: add more integ tests for datasets API

- solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
N/A
Harden paab test cases and file cleanup.
Checklist:
> chore: harden paab tests

- solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts
> chore: update test description 

- solutions/swb-reference/README.md
- solutions/swb-reference/RSW.openapi.json
- solutions/swb-reference/RSW.postman_collection.json
N/A
Update API collection examples.
Checklist:
> fix: collection examples

- solutions/swb-reference/jest.config.js
> chore: add back ts to jest options for moduleFileExtensions

- deployment/build-s3-dist.sh
- solutions/swb-reference/README_SOLUTIONS.md
- solutions/swb-reference/scripts/solutions-implementation/baseResourceSetup.sh
- solutions/swb-reference/scripts/solutions-implementation/postSolutionDeployment.sh
N/A
Update solutions template name.
Checklist:
> fix: solutions template name

- solutions/swb-reference/integration-tests/config/swbv2-private.yaml
- solutions/swb-reference/integration-tests/config/testEnv.yaml
* Update resources used by stage integ tests
Checklist:
> chore: update resources used by stage integ tests

- README.md
- common/changes/@aws/swb-app/atmikev-GALI-2336-CostCenterAccountStatus_2023-06-21-18-24.json
- common/changes/@aws/swb-reference/atmikev-GALI-2336-CostCenterAccountStatus_2023-06-22-18-28.json
- common/changes/@aws/workbench-core-accounts/atmikev-GALI-2336-CostCenterAccountStatus_2023-06-21-18-24.json
- common/config/rush/pnpm-config.json
- solutions/swb-app/src/costCenterRoutes.ts
- solutions/swb-reference/scripts/runLocally.sh
- workbench-core/accounts/src/errors/InvalidAccountStateError.ts
- workbench-core/accounts/src/errors/errors.test.ts
- workbench-core/accounts/src/index.ts
- workbench-core/accounts/src/services/costCenterService.test.ts
- workbench-core/accounts/src/services/costCenterService.ts
Throw a 400 if the account being used to create the cost center is not in the `CURRENT` state.
> feat: cost center account status error

- common/changes/@aws/swb-reference/janeyu-externalID_2023-06-15-18-26.json
- common/changes/@aws/workbench-core-environments/janeyu-externalID_2023-06-15-18-26.json
- solutions/swb-reference/integration-tests/config/example.yaml
- solutions/swb-reference/integration-tests/config/release-candidate-private.yaml
- solutions/swb-reference/integration-tests/config/release-candidate.yaml
- solutions/swb-reference/integration-tests/config/swbv2-private.yaml
- solutions/swb-reference/integration-tests/config/testEnv.yaml
- solutions/swb-reference/integration-tests/support/utils/settings.ts
- solutions/swb-reference/integration-tests/tests/multiStep/awsAccount.test.ts
- workbench-core/environments/src/handlers/statusHandler.test.ts
- workbench-core/environments/src/services/environmentService.test.ts
Issue #, if available: GALI-2509
* Replace hardcoded external ID values in integration tests with values supplied via the config settings file.
* Replace hardcoded external ID values in unit tests with values with sample value
Checklist:
> chore: mask externalId

- .github/workflows/npm-publish.yml
- deployment/build-s3-dist.sh
- solutions/swb-reference/README.md
- solutions/swb-reference/README_SOLUTIONS.md
- solutions/swb-reference/RSW.openapi.json
- solutions/swb-reference/RSW.postman_collection.json
- solutions/swb-reference/scripts/solutions-implementation/baseResourceSetup.sh
- solutions/swb-reference/scripts/solutions-implementation/postSolutionDeployment.sh
Merging commits on main into develop to avoid merge conflicts in automatic PRs based off of main
Checklist:
> chore: merge main to develop
