aws-solutions/research-service-workbench-on-aws

solutions/swb-reference/scripts/runLocally.sh
A config file can have comments in it like shown below
```
stage: dev
awsRegion: us-east-2
awsRegionShortName: oh #two or three letter abbreviation for the region. You can choose your own abbreviation
```
In this case `awsRegionShortName` has a comment in it specified by `#`. The bash script only parse the last word in a line, which is not accurate. In this case it should remove all text after `#` before grabbing the last word in the line.
Checklist:
=> fix: runLocally script

common/changes/@aws/workbench-core-authentication/fix-authn-verify-token-fix_2022-08-16-19-54.json, workbench-core/authentication/src/authenticationMiddleware.ts
Fixed bug where verifyToken in authenticationMiddleware still used Authorization header for token verification
Checklist:
=> fix: authN verify token fix

solutions/swb-reference/integration-tests/tests/isolated/environments/get.test.ts
Description of changes: Added negative integration tests for:
* GetEnvironment on an environment that does not exist
* GetEnvironmentConnection on an environment that does not exist
Checklist:
=> test(swb-reference): adding GetEnvironment and GetEnvironmentConnection integ tests

common/config/rush/pnpm-lock.yaml, solutions/swb-reference/package.json, solutions/swb-reference/src/environment/workflow.ts
GALI-1663
Replaced `cdk-ssm-document` with `CfnDocument` provided by CDK. 
**Testing**
* If SSM document changed, a new version is created in AWS account
* If SSM document is not changed, no changes are made to SSM documents in AWS account
Checklist:
=> fix: use CfnDocument

solutions/swb-ui/infrastructure/package.json, solutions/swb-ui/infrastructure/src/constants.ts
…ine check
GALI-1863
Allow cdk synth for swb-ui without stage file ,so we can run pipeline checks on cdk template
Checklist:
* [x ] Have you successfully deployed to an AWS account with your changes?
=> fix: allow cdk synth in swb-ui without stage file

solutions/swb-reference/src/SWBStack.ts, solutions/swb-reference/src/config/example.yaml, solutions/swb-ui/infrastructure/src/SWBUIStack.ts, solutions/swb-ui/infrastructure/src/hosting-infra/ecs-cluster.ts
GALI-1540
Use CDK to set up an ECS cluster that runs a dummy task
These ECS instances should be able to accept custom network
Use the values specified in BYON design for setting up auto-scaling
Checklist:
=> feat: Create ECS cluster

.viperlightignore, common/changes/@aws/workbench-core-base/fix-viperlight-scans_2022-10-18-18-17.json, solutions/swb-reference/integration-tests/config/example.yaml, solutions/swb-reference/integration-tests/config/testEnv.yaml, solutions/swb-reference/integration-tests/support/setup.ts, solutions/swb-reference/integration-tests/support/utils/settings.ts, solutions/swb-reference/scripts/generateCognitoTokens.js, solutions/swb-reference/src/config/demo.yaml, solutions/swb-reference/src/config/example.yaml, solutions/swb-reference/src/config/testEnv.yaml, solutions/swb-reference/src/constants.ts, solutions/swb-reference/src/postDeployment.ts, workbench-core/base/src/cognitoTokenService.ts
* Remove email from config files. Username is now pulled from SSM param store, instead of hard coding it in the config file. This is the same as what we are currently doing with password.
* Disable viperlight warnings for false positive cases
Checklist:
=> fix: viperlight scans

.github/workflows/check-and-add-license-header.yml, .github/workflows/create-release-branch.yml, .github/workflows/create-release-pr-to-main.yml, .github/workflows/enable-feat-protection.yml, .github/workflows/feat-deletion.yml, .github/workflows/merge-develop-to-stage.yml, .github/workflows/merge-release-pr-to-main.yml, .github/workflows/publish-and-merge-to-develop.yml, .github/workflows/readme-commit.yml
1. `create-release-pr-to-main.yml`:
1. Manually trigger this workflow to create a PR from `release/*` branch to `main` branch
2. Should be triggered from `release/*` branch
3. `merge-develop-to-stage.yml`: Updates to enable merge commit and disable merge commit after the merge is done
4. `merge-release-pr-to-main.yml`:  Maunally trigger this workflow to merge the `release/*` branch PR to `main`. 
1. Input: PR number of the PR created by `create-release-pr-to-main.yml` as input. 
2. This workflow performs following steps:
1. enables merge commits
2. Performs merge commit to `main` branch
3. disables merge commit
3. Only `admins` allowed to merge
4. Added a check to make sure this workflow is being used to merge PRs with source branch starting …
=> chore: gh workflow update

common/changes/@aws/workbench-core-environments/patch-post-deployment-script-update_2022-10-20-22-12.json, workbench-core/environments/src/postDeployment/serviceCatalogSetup.ts
- Updated `serviceCatalogSetup` to use the `path` module to parse file path rather than parsing manually per [this StackOverflow post](https://stackoverflow.com/questions/423376/how-to-get-the-file-name-from-a-full-path-using-javascript) 
Checklist:
=> fix(swb-reference): updated postDeployment file path parsing

solutions/swb-reference/integration-tests/support/clientSession.ts, solutions/swb-reference/integration-tests/support/utils/HttpError.ts, solutions/swb-reference/integration-tests/support/utils/settings.ts, solutions/swb-reference/src/SWBStack.ts, solutions/swb-reference/src/constants.ts, solutions/swb-reference/src/proxyHandlerLambda.ts, solutions/swb-ui/infrastructure/src/SWBUIStack.ts, solutions/swb-ui/infrastructure/src/constants.ts
GALI-1547
- ALB must return an HTTP Error response instead of throwing one to avoid generic Bad Gateway response.
- Changes made to make integration tests backwards compatible with the use of `http:<ALB DNS Name>` base URL.
Checklist:
=> fix: consistent error response from ALB vs APIGW

common/changes/@aws/swb-app/maghirardelli-gali-1739-list-project-api_2022-10-28-16-33.json, common/changes/@aws/workbench-core-accounts/maghirardelli-gali-1739-list-project-api_2022-10-28-16-33.json, common/changes/@aws/workbench-core-base/maghirardelli-gali-1739-list-project-api_2022-10-28-16-33.json, common/changes/@aws/workbench-core-environments/maghirardelli-gali-1739-list-project-api_2022-10-28-16-33.json, common/config/rush/pnpm-lock.yaml, solutions/swb-app/src/projectRoutes.ts, solutions/swb-app/src/schemas/projects/listProjectsSchema.ts, solutions/swb-reference/SWBv2.postman_collection.json, workbench-core/accounts/README.md, workbench-core/accounts/src/index.ts, workbench-core/accounts/src/models/listProjectsRequest.ts, workbench-core/accounts/src/models/listProjectsResponse.ts, workbench-core/accounts/src/services/projectService.test.ts, workbench-core/accounts/src/services/projectService.ts, workbench-core/base/README.md, workbench-core/base/package.json, workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts, workbench-core/base/src/aws/helpers/dynamoDB/getter.test.ts, workbench-core/base/src/constants/queryParams.ts, workbench-core/base/src/index.ts, workbench-core/base/src/utilities/paginationHelper.test.ts, workbench-core/base/src/utilities/paginationHelper.ts, workbench-core/environments/README.md, workbench-core/environments/src/services/environmentService.ts, workbench-core/environments/src/services/environmentTypeConfigService.ts, workbench-core/environments/src/services/environmentTypeService.ts
Issue #, if available: GALI-1739
Updated the List Projects API to support pagination and prepare for dynamic Authz integration to enforce project as a boundary.
Integ tests to come but I extensively tested the API manually through postman
I also did a small refactor to reuse pagination code and custom object types
Checklist:
=> feat(pb): update LIST Projects API

common/changes/@aws/workbench-core-accounts/fix-costCenter-check-dependency_2022-11-22-21-49.json, workbench-core/accounts/src/services/costCenterService.ts
fix: checkDepdendency should return Promise<void> not void
Checklist:
=> fix: cost center checkDependency

solutions/swb-app/src/generateRouter.ts, solutions/swb-app/src/projectRoutes.ts, solutions/swb-app/src/schemas/projects/projectMetadataParser.ts, workbench-core/accounts/src/services/projectService.test.ts, workbench-core/accounts/src/services/projectService.ts
Issue #, if available: GALI-1738 fast follow
Refactor the soft DELETE Project API to use MetadataService since there is common code
Checklist:
=> fix(projects): DELETE project API uses MetadataService

.github/workflows/merge-commit-topic-branch-pr-to-feat-branch.yml, .github/workflows/merge-release-pr-to-main.yml
1. Adds a workflow (`merge-commit-topic-branch-pr-to-feat-branch.yml`) that can be triggered manually to perform merge commits from topic branches to feat/* branches
2. Fix for `merge-release-pr-to-main.yml` workflow: `tj-actions/branch-names` github action does not work on workflow_dispatch event
Note:
`merge-commit-topic-branch-pr-to-feat-branch.yml` workflow won't be activated on github UI until this workflow is merged to `main` branch. As a workaround you can install [gh cli](https://cli.github.com/) and trigger the following command when you need to perform merge commits on feat/* branches from your topic branch: `gh workflow run 'Merge-commit-topic-branch-pr-to-feat-branches' --ref <TOPIC_BRANCH_NAME> -f pr_number=<PR_NUMBER> -f …
=> chore: allow merge commits to feat/* branches

solutions/swb-app/src/accountRoutes.ts, solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/update.test.ts, workbench-core/accounts/README.md, workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts, workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
GALI-2036
Make `name` the only param that can be updated on an account
Checklist:
=> feat: GALI-2036 update account

workbench-core/example/infrastructure/README.md
Script getResource.sh requires jq to run correctly; this tool is not mentioned in prerequisites
Issue #, if available: N/A
Aadding [jq](https://stedolan.github.io/jq/) CLI tool to prerequisites step of workbench-core/example/infrastructure/README.md
=> docs(readme.md): adding jq to prerequisites

solutions/swb-reference/src/SWBStack.ts, solutions/swb-reference/src/constants.ts, solutions/swb-ui/infrastructure/src/constants.ts, solutions/swb-ui/ui/scripts/image-deploy.sh
BREAKING CHANGE: UI stack uses previous Cfn Export name, which requires UI stack to be deleted prior to updating swb-reference
* Update account id to be grabbed from env so that existing VPC can be used in SWB
* Update Cfn Export name for Access Log Bucket to allow for multiple installations of SWB in the same region in the same account
Checklist:
=> fix(swb): fix accountId needed for using an existing VPC and update AccessLog Cfn Export name

solutions/swb-reference/integration-tests/config/testEnv.yaml, solutions/swb-reference/integration-tests/support/setup.ts, solutions/swb-reference/integration-tests/support/utils/settings.ts, workbench-core/example/infrastructure/integration-tests/support/setup.ts
When merging in the `awsAccount` feature branch, I failed to notice that there was not a default value set for `hostingAccountHandlerRoleArn` in the `testEnv.yaml` file which gets used when running integration tests after merge. I've added a value, so tests should now run.
=> chore: update github's hostingAccountHandlerRoleArn value for integration tests

common/changes/@aws/swb-app/atmikev-GALI-2125_AddFieldsToDataSetCreation_2022-12-21-16-55.json, common/changes/@aws/workbench-core-base/atmikev-GALI-2125_AddFieldsToDataSetCreation_2022-12-21-16-55.json, common/changes/@aws/workbench-core-datasets/atmikev-GALI-2125_AddFieldsToDataSetCreation_2022-12-21-00-43.json, solutions/swb-app/src/dataSetRoutes.ts, solutions/swb-reference/SWBv2.postman_collection.json, solutions/swb-reference/integration-tests/support/resources/datasets/datasets.ts, solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts, solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts, workbench-core/base/README.md, workbench-core/datasets/src/schemas/createDataSet.ts, workbench-core/example/infrastructure/integration-tests/support/resources/datasets/datasets.ts
Added `owner` and `type` as required fields for `DataSet` creation. Fixed bug where `datasetName` was being used on the Create request instead of `name`, which is the field on the actual object.
Updated schema and integration tests.
=> feat: [GALI-2125] add fields to data set creation

common/changes/@aws/workbench-core-authorization/fix-group-management-fixes_2023-01-04-00-10.json, workbench-core/authorization/README.md, workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts, workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts, workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts, workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts, workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
- Added check to `createGroup` to not allow groups to be created if theyre pending delete
- Added check to `setGroupStatus` to not allow status to go from `delete_pending` to `active`
- Added/updated corresponding unit/integration tests
Checklist:
=> fix: group management fixes

solutions/swb-reference/src/errors.ts, solutions/swb-reference/src/utils/roleUtils.test.ts, solutions/swb-reference/src/utils/roleUtils.ts
* Add roleUtils for getting role/group names for ITAdmin, ProjectAdmin, and Researcher
Checklist:
=> feat(swb-ref): add roleUtils

solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts, solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/update.test.ts
Fixes the integ tests that failed here
https://github.com/aws-solutions/solution-spark-on-aws/actions/runs/3906737149/jobs/6675321781
* The isolated accounts test failed because switching to Zod parser caused the error message to look different from what the tests expected.
* The costCenter test failed because the account DDB entry was missing the `name` field in the test environment. I manually fixed that in the test environment. 
Checklist:
=> test: account integ tests

workbench-core/example/infrastructure/integration-tests/support/clientSession.ts, workbench-core/example/infrastructure/integration-tests/support/resources/authentication/authentication.ts, workbench-core/example/infrastructure/integration-tests/support/setup.ts, workbench-core/example/infrastructure/integration-tests/tests/authentication/routeHandler.test.ts
- Added integration tests for the authentication package's `refreshAccessToken` API
Checklist:
=> test: added refreshAccessToken integration tests

workbench-core/example/infrastructure/integration-tests/support/resources/authentication/authentication.ts, workbench-core/example/infrastructure/integration-tests/tests/authentication/routeHandler.test.ts
- added integration tests for the authentication package's `getTokensFromAuthorizationCode` API
Checklist:
=> test: added integration tests for getTokensFromAuthorizationCode

common/changes/@aws/swb-app/kevpark-update-env-params-fix_2023-02-16-16-52.json, solutions/swb-app/src/projectEnvironmentRoutes.ts, solutions/swb-app/src/projectEnvs/projectEnvPlugin.ts, solutions/swb-reference/integration-tests/support/resources/environments/environments.ts
* Updated order of params for projectEnvironmentService/Plugin so that Project always comes first.
Checklist:
=> fix: updateEnvironment params order was backwards

common/changes/@aws/swb-app/maghirardelli-fix-ssh-key-route-mapping_2023-02-16-21-03.json, solutions/swb-app/src/staticRouteConfig.ts
fixing static route config. The merge resolution created two mappings of the same route to different permissions, overwriting one needed for the integ tests.
Checklist:
=> fix(ssh-keys): fix ssh keys route mapping to not have duplicate

solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
add afterEach to cleanup after integ test suite so environments don't stick around
Checklist:
=> fix(integ tests): add afterEach step to cleanup environments

common/changes/@aws/swb-app/atmikev-GALI-2279_ListDataSetAccessPermissions_2023-02-20-22-54.json, common/changes/@aws/workbench-core-accounts/atmikev-GALI-2279_ListDataSetAccessPermissions_2023-02-20-23-01.json, common/changes/@aws/workbench-core-datasets/atmikev-GALI-2279_ListDataSetAccessPermissions_2023-02-20-22-54.json, solutions/swb-app/README.md, solutions/swb-app/src/dataSetRoutes.ts, solutions/swb-app/src/dataSets/dataSetPlugin.ts, solutions/swb-app/src/dataSets/listDataSetAccessPermissionsRequestParser.ts, solutions/swb-app/src/staticPermissionsConfig.ts, solutions/swb-app/src/staticRouteConfig.ts, solutions/swb-reference/README.md, solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts, solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts, solutions/swb-reference/src/services/dataSetService.test.ts, solutions/swb-reference/src/services/dataSetService.ts, workbench-core/accounts/README.md, workbench-core/datasets/src/dataSetService.ts
Added endpoint and tests to allow a user to get the permissions associated with a data set so they can see who has access to their dataset
Checklist:
=> feat: list data set access permissions

solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
- fixed ordering of dataset permissions in datasets multistep integ test
Checklist:
=> fix: datasets integ test fix

common/changes/@aws/swb-app/kevpark-paab-happy-path_2023-02-25-05-01.json, solutions/swb-app/src/dataSetRoutes.ts, solutions/swb-reference/integration-tests/support/models/environmentTypeConfigs.ts, solutions/swb-reference/integration-tests/support/models/projects.ts, solutions/swb-reference/integration-tests/support/resources/environmentTypeConfigs/environmentTypeConfig.ts, solutions/swb-reference/integration-tests/support/resources/environments/environment.ts, solutions/swb-reference/integration-tests/support/utils/constants.ts, solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts, solutions/swb-reference/src/dynamicRouteConfig.ts, solutions/swb-reference/src/postDeployment/authorizationSetup.ts, solutions/swb-reference/src/services/swbProjectService.ts
* Add happy path integ test for project as a boundary
* Add GetDataset route for ITAdmin only to be used for integ tests
* Update ITAdmin Dataset permissions so that they can only GetDataset
Checklist:
=> feat: project as a Boundary integ test and GetDataset route

common/changes/@aws/workbench-core-datasets/fix-revert-create-dataset-schema-change_2023-02-27-18-32.json, workbench-core/datasets/src/schemas/createDataSet.ts
- reverted accidental change to `CreateDataSet` schema object
Checklist:
=> fix: revert change to CreateDataSet schema object

solutions/swb-reference/integration-tests/tests/isolated/costCenter/create.test.ts
Tests check the message that gets returned instead of having a set of data that lets the user know what went wrong. I forgot to update that.
=> chore: cost center test fix

.github/workflows/deploy-integration-swb-reference-byon.yml, .github/workflows/deploy-integration-swb-reference.yml
* swb-reference and swb-reference-byon github workflow assume roles increased to 2 hours to avoid timeout
Checklist:
=> feat: increase github workflow assume role for swb-reference to 2 hours

solutions/swb-reference/integration-tests/support/resources/sshKeys/sshKey.ts, solutions/swb-reference/integration-tests/tests/isolated/sshKeys/create.test.ts
Fix cleanup for ssh key to use purge, not delete, since the delete is a hard delete and we added a purge route
Fix message of an error in the test to match actually thrown error
Checklist:
=> test(sshkeys): fix create test and delete

sonar-project.properties
GALI-2027
Adding lcov paths for NightsWatch Sonar Qube coverage report.
Checklist:
=> chore: adding sonarqube coverage paths

solutions/swb-reference/src/SWBStack.ts
Issue #, if available: GALI-2397
set ELB V2 Listener to use ELBSecurityPolicy-TLS13-1-2-2021-06 security policy in place of ELBSecurityPolicy-2016-08
Checklist:
=> fix(appsec): update listener SSL policy

common/changes/@aws/swb-app/farandac-validate-env-project_2023-04-06-15-57.json, solutions/swb-app/src/projectEnvironmentRoutes.ts, solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
GALI-2437
-Validate environment is part of a project on get Request
-Add integ test validating project belongs to environment on environment APIs
Checklist:
=> chore: validate environment belongs to project on APIs

sonar-project.properties
N/A
Ignore js files in sonar scanning since build/lib exclusion isn't taking effect.
Checklist:
=> fix: ignore js files from sonar scans

sonar-project.properties
N/A
Ignore build and lib folders for sonar scan.
Checklist:
=> fix: ignore build folders for sonar scan

common/changes/@aws/workbench-core-base/janeyu-zodModel_2023-04-19-21-57.json, workbench-core/base/src/utilities/textUtil.ts, workbench-core/base/src/utilities/validatorHelper.test.ts, workbench-core/base/src/utilities/validatorHelper.ts
Issue #, if available: GALI-2327
Create Zod models we can reuse for regex strings. New methods
* nonHTML 
* swbName with max length and valid char
* swbDescription with max length and valid char
Checklist:
=> chore(zod): add zod model for regex

common/config/rush/pnpm-config.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, solutions/swb-reference/src/services/dataSetService.ts
Issue #, if available: GALI-2409
2 minutes TTL for S3 presigned URL for upload files to dataset based on the fact that we need our customers to manually interact with the URL and human interaction requires a reasonable time limit that is feasible to then use this URL. If we automate the interaction with the presigned URL in the future, we can shorten it even more.
I have manually tested that this time limit is reasonable and that it is imposed by this code change.
Checklist:
=> fix(swb datsets): shorten TTL for 2 min for upload to dataset

common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, solutions/swb-reference/SWBv2.openapi.json, solutions/swb-reference/SWBv2.postman_collection.json, solutions/swb-reference/package.json, solutions/swb-reference/scripts/generateCodeChallenge.js
* Add auth APIs to postman and openapi collections
* Add script to generate code challenge and verifiers used for login/exchange auth code
Checklist:
=> feat(swb-ref): adding auth APIs to postman/openapi collections

common/changes/@aws/swb-app/farandac-et-input-validation_2023-04-26-05-30.json, common/changes/@aws/workbench-core-base/farandac-et-input-validation_2023-04-26-05-30.json, common/changes/@aws/workbench-core-environments/farandac-et-input-validation_2023-04-26-05-30.json, solutions/swb-app/src/environmentRoutes.ts, solutions/swb-app/src/environmentTypeRoutes.ts, solutions/swb-app/src/projectEnvTypeConfigRoutes.ts, solutions/swb-reference/integration-tests/support/utils/utilities.ts, solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/get.test.ts, solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/list.test.ts, solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/update.test.ts, solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts, solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts, workbench-core/base/config/jest.config.json, workbench-core/base/src/index.ts, workbench-core/base/src/interfaces/queryStringParamFilter.ts, workbench-core/base/src/utilities/textUtil.test.ts, workbench-core/base/src/utilities/textUtil.ts, workbench-core/base/src/utilities/validatorHelper.test.ts, workbench-core/base/src/utilities/validatorHelper.ts, workbench-core/environments/config/jest.config.json, workbench-core/environments/src/index.ts, workbench-core/environments/src/models/environmentTypes/getEnvironmentTypesRequest.ts, workbench-core/environments/src/models/environmentTypes/listEnvironmentTypesRequest.ts, workbench-core/environments/src/models/environmentTypes/updateEnvironmentTypeRequest.ts
GALI-2321
GALI-2319
Add length validation to query params
Add length and format validation to environment type routes
Add length and format validation to environment List route
Centralize validation messages
Add Zod to get ET
Add integ tests for length validation
Checklist:
=> chore(env list, et routes): add input length and format validation

solutions/swb-reference/src/SWBStack.ts
Issue #, if available:V869865466
Update access log bucket config to be HTTPS only
Checklist:
=> fix(AppSec): s3 accesslog bucket only accept HTTPS

solutions/swb-reference/src/SWBStack.ts
* SageMaker resources are created with lowercase resource names due to CloudFormation. Updating IAM policies to be case insensitive with IAM Policies to account for both lower case and Pascal case.
Checklist:
=> fix(swb-ref): make SageMaker IAM policy case insensitive

common/changes/@aws/workbench-core-user-management/janeyu-cognitoLimit_2023-05-12-23-46.json, workbench-core/user-management/src/errors/errors.test.ts, workbench-core/user-management/src/errors/userRolesExceedLimitError.ts, workbench-core/user-management/src/index.ts, workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts, workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
Issue #, if available: P88136850
* add user group limit 25 to cognitoUserManagement
* update unit test
Checklist:
=> chore(user-management): add cognito group limit 25

common/changes/@aws/workbench-core-base/janeyu-zodFilterBetween_2023-05-12-17-14.json, solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts, solutions/swb-reference/integration-tests/tests/isolated/projects/list.test.ts, workbench-core/base/src/index.ts, workbench-core/base/src/interfaces/queryStringParamFilter.ts, workbench-core/base/src/utilities/textUtil.ts
Issue #, if available:P88136656
* Filter parser should return 4xx error when given filter between val1 <= val2
* All List APIs (list env & list project) have been verified to return 4xx errors instead of 5xx error when given a start date that is later than end date for createdAt timestamp 
Checklist:
=> chore(zod): filter between val1<=val2

solutions/swb-reference/integration-tests/support/resources/accounts/account.ts, solutions/swb-reference/src/backendAPI.ts
comment out the cleanup steps that are destroying functionality in deployments (we will revisit a better way to do the test and cleanup later)
make ttl for temp project creds 60 min in line with access token validity
Checklist:
=> fix: unblock pipeline with longer ttl on temp creds and no account cleanup

.viperlightignore, common/changes/@aws/workbench-core-environments/janeyu-viperignore_2023-05-18-19-33.json, common/changes/@aws/workbench-core-infrastructure/janeyu-viperignore_2023-05-18-19-33.json, solutions/swb-reference/scripts/setupIntegTestEnv.sh, solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentConnectionService.test.ts, workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts, workbench-core/infrastructure/src/workbenchAppRegistry.test.ts
Issue #, if available: GALI-2462
fake test data has to come from the list of authorized fictitious data: https://alpha.www.docs.aws.a2z.com/awsstyleguide/latest/styleguide/safenames.html, which .viperlight automatically ignores
Checklist:
=> chore(viperlight): replace with authorized creds

common/changes/@aws/workbench-core-accounts/thingut-account-onboarding-status_2023-05-18-19-38.json, workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts, workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
* Update account handler to check `onboard-account-byon.cfn.yml`, `onboard-account-tgw.cfn.yml`, and `onboard-account.cfn.yml` so if users have a hosting account that isn't `onboard-account.cfn.yml`, their account status is correct.
Testing
* This works with `onboard-account.cfn.yml` and `onboard-account-byon.cfn.yml`. I didn't test it with `onboard-account-tgw.cfn.yml`, but it follows the same logic as BYON and should work as expected. 
Checklist:
*  [x] Have you successfully deployed to an AWS account with your changes?
=> fix(account-status): working account status update for byon

common/changes/@aws/workbench-core-accounts/maghirardelli-fix-account-test_2023-05-26-17-23.json, solutions/swb-reference/README.md, solutions/swb-reference/integration-tests/config/example.yaml, solutions/swb-reference/integration-tests/support/complex/accountHelper.ts, solutions/swb-reference/integration-tests/support/resources/accounts/account.ts, solutions/swb-reference/integration-tests/support/setup.ts, solutions/swb-reference/integration-tests/support/utils/settings.ts, solutions/swb-reference/integration-tests/tests/multiStep/awsAccount.test.ts, solutions/swb-reference/scripts/setupIntegTestEnv.sh, workbench-core/accounts/src/services/accountService.ts
Issue #, if available: GALI-2497
Re-do the test logic to not have conflicting resources.
This now requires you to supply a AWS Account ID that is neither a hosting nor main account for the deployment you are testing against. Because of this, I made the test conditionally run so customers do not have to run the account test if the additional account is too much overhead. For devs, we are fine with this additional prereq.
Now comes in _**Optional!**_
Checklist:
=> test(account): redo account multistep integ test

common/changes/@aws/swb-app/thingut-hosting-account-validation_2023-06-04-16-21.json, common/changes/@aws/workbench-core-accounts/thingut-hosting-account-validation_2023-06-04-16-13.json, common/changes/@aws/workbench-core-base/thingut-hosting-account-validation_2023-06-04-16-21.json, solutions/swb-app/src/accountRoutes.ts, solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts, workbench-core/accounts/src/errors/InvalidAwsAccountIdError.ts, workbench-core/accounts/src/errors/errors.test.ts, workbench-core/accounts/src/index.ts, workbench-core/accounts/src/models/accounts/createAccountRequest.ts, workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts, workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts, workbench-core/base/src/utilities/textUtil.ts, workbench-core/base/src/utilities/validatorHelper.ts
Add additional Input validation for creating new hosting accounts
* User must provide an `awsAccountId` of a real account
* `envMgmtRoleArn` and `hostingAccountHandlerRole` arn must follow the proper ARN format. 
Checklist:
=> fix: create account should throw 400 error instead of 500 errors for incorrect accountId and arns

common/changes/@aws/swb-app/release-v2.0.0_2023-06-05-09-05.json, common/changes/@aws/workbench-core-base/release-v2.0.0_2023-06-05-09-05.json, common/changes/@aws/workbench-core-environments/release-v2.0.0_2023-06-05-09-05.json, solutions/swb-app/src/dataSetRoutes.ts, solutions/swb-app/src/dataSets/dataSetPlugin.ts, solutions/swb-app/src/dataSets/isProjectAuthorizedForDatasetsParser.ts, solutions/swb-app/src/dataSets/verifyProjectAccessForDatasetsParser.ts, solutions/swb-app/src/generateRouter.ts, solutions/swb-app/src/index.ts, solutions/swb-app/src/projectEnvironmentRoutes.ts, solutions/swb-app/src/schemas/projects/projectMetadataParser.ts, solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts, solutions/swb-reference/integration-tests/tests/isolated/datasets/uploadFile.test.ts, solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts, solutions/swb-reference/src/services/dataSetService.test.ts, solutions/swb-reference/src/services/dataSetService.ts, workbench-core/base/src/aws/helpers/dynamoDB/ddbUtil.test.ts, workbench-core/base/src/aws/helpers/dynamoDB/ddbUtil.ts, workbench-core/base/src/index.ts, workbench-core/environments/src/services/environmentService.ts, workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts, workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
* If a Dataset is still mounted on an environment, the project of that environment cannot have its access removed until that environment has been terminated
* Fixed bug where project losing access to a Dataset was not removing its access to upload file API
* Added integ tests to make sure a user in two projects, but only one project has access to a dataset, does not carry over the permissions from one project to another
* Environment creation given a Dataset that they do not have access to throws a 403 error and does not create an entry for the failed environment in the database
* Fixed incorrect project to dataset metadata that used the wrong resource type
* Fixed dataset permissions to include condition on projectId so that users will no longer be able to pass in …
=> fix: fix Dataset Edge Cases

common/changes/@aws/workbench-core-accounts/thingut-hosting-account-text-limit_2023-06-05-17-34.json, common/changes/@aws/workbench-core-base/thingut-hosting-account-text-limit_2023-06-05-17-34.json, solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts, workbench-core/accounts/src/models/accounts/createAccountRequest.ts, workbench-core/base/src/utilities/textUtil.test.ts, workbench-core/base/src/utilities/textUtil.ts, workbench-core/base/src/utilities/validatorHelper.test.ts, workbench-core/base/src/utilities/validatorHelper.ts
fix: set maximum input length for create account requests
Max Arn length is 2048, min is 20, so we'll set the max length as 400 for RSW
https://docs.aws.amazon.com/IAM/latest/APIReference/API_Policy.html
External id max length is 1224. so wel'll set the max length as 400 for RSW
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html
Checklist:
=> fix: set maximum input length for create account requests

solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts, solutions/swb-reference/src/services/dataSetService.test.ts, solutions/swb-reference/src/services/dataSetService.ts
* Associating/disassociating a project that owns a dataset will throw a 4xx error
Checklist:
=> fix: address edge cases for adding/removing owning project to dataset

common/changes/@aws/workbench-core-base/yanyu-cognito-fix_2023-06-05-19-46.json, common/changes/@aws/workbench-core-user-management/yanyu-cognito-fix_2023-06-05-19-46.json, workbench-core/base/src/aws/awsService.ts, workbench-core/base/src/aws/helpers/cognitoService.test.ts, workbench-core/base/src/aws/helpers/cognitoService.ts, workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts, workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
* Deployed to AWS account 
* Tested with users having 30+ roles, verified all roles are retrieved successfully 
Checklist:
=> fix: add pagination to get user roles call

solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
* Updated status polling for paab helper to only look at desired state rather than transition state, while short circuiting if status contains "FAIL"
Checklist:
=> test(swb-ref): fix paab state change polling

common/changes/@aws/swb-reference/janeyu-pageSize_2023-06-27-20-55.json, solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
Description of changes: V900862033
Checklist:
add  integ tests to prove the two api calls (listEnvironments or listProjectEnvironments) have a limit of 100 pageSize
=> chore(list-env): add integ test for pageSize exceed max

common/changes/@aws/swb-reference/chore-main-hosting-same_2023-07-05-18-07.json, common/changes/@aws/workbench-core-accounts/chore-main-hosting-same_2023-07-05-18-07.json, solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml, solutions/swb-reference/src/templates/onboard-account.cfn.yaml, workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts, workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
GALI-1567
- Skipped a few post deployment steps to ensure main account can be onboarded as hosting account.
- Verified workspace launch/stop/start/terminate work as expected
- Verified AccountHandler lambda runs successfully
- Verified postDeployment script runs successfully
Checklist:
=> feat: main equal to hosting
